#!/bin/bash

textOfFrame="$1"
lenOfFrame=$(($(wc -c <<< "$textOfFrame")+1))

print_border() {
	printf "+"

	for((i=0; i<"$lenOfFrame"; i++)); do
		printf "-"
	done

	printf "+\n"
}

print_border
printf "| %s |\n" "$textOfFrame"
print_border
